theme: jekyll-theme-minimal
title: Rajesh Shreedhar Bhat
logo: photo.jpg
description: Staff Data Scientist at Walmart Global Tech | Computer Vision & ML Expert | Speaker & Author
email: rsbhat@asu.edu
linkedin_username: rajeshshreedhar
github_username: rajesh-bhat
